### ISSUE TITLE
Swift 4.1.1 Build Error

### ISSUE THREAD

**Issue by RockfordWei** [PerfectlySoft/Perfect-CRUD#41]
```
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:142:11: error: 'loggingQueue' is inaccessible due to 'private' protection level
                        return loggingQueue.sync { return _queryLogDestinations }
                               ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:142:38: error: '_queryLogDestinations' is inaccessible due to 'private' protection level
                        return loggingQueue.sync { return _queryLogDestinations }
                                                          ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:97:21: note: '_queryLogDestinations' declared here
        private static var _queryLogDestinations: [CRUDLogDestination] = [.console]
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:139:4: error: 'loggingQueue' is inaccessible due to 'private' protection level
                        loggingQueue.async { _queryLogDestinations = newValue }
                        ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:139:25: error: '_queryLogDestinations' is inaccessible due to 'private' protection level
                        loggingQueue.async { _queryLogDestinations = newValue }
                                             ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:97:21: note: '_queryLogDestinations' declared here
        private static var _queryLogDestinations: [CRUDLogDestination] = [.console]
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:150:11: error: 'loggingQueue' is inaccessible due to 'private' protection level
                        return loggingQueue.sync { return _errorLogDestinations }
                               ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:150:38: error: '_errorLogDestinations' is inaccessible due to 'private' protection level
                        return loggingQueue.sync { return _errorLogDestinations }
                                                          ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:98:21: note: '_errorLogDestinations' declared here
        private static var _errorLogDestinations: [CRUDLogDestination] = [.console]
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:147:4: error: 'loggingQueue' is inaccessible due to 'private' protection level
                        loggingQueue.async { _errorLogDestinations = newValue }
                        ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:147:25: error: '_errorLogDestinations' is inaccessible due to 'private' protection level
                        loggingQueue.async { _errorLogDestinations = newValue }
                                             ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:98:21: note: '_errorLogDestinations' declared here
        private static var _errorLogDestinations: [CRUDLogDestination] = [.console]
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:133:3: error: 'loggingQueue' is inaccessible due to 'private' protection level
                loggingQueue.sync {
                ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:134:4: error: 'logCheckInSerialQueue' is inaccessible due to 'private' protection level
                        logCheckInSerialQueue()
                        ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:109:22: note: 'logCheckInSerialQueue()' declared here
        private static func logCheckInSerialQueue() {
                            ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:161:3: error: 'loggingQueue' is inaccessible due to 'private' protection level
                loggingQueue.async {
                ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:100:21: note: 'loggingQueue' declared here
        private static var loggingQueue: DispatchQueue = {
                           ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:162:4: error: 'pendingEvents' is inaccessible due to 'private' protection level
                        pendingEvents.append(.init(time: now, type: type, msg: msg))
                        ^
/tmp/swtest/.build/checkouts/Perfect-CRUD-4656286903651146499/Sources/PerfectCRUD/Logging.swift:99:21: note: 'pendingEvents' declared here
        private static var pendingEvents: [CRUDLogEvent] = []
                           ^
error: terminated(1): /usr/bin/swift-build-tool -f /tmp/swtest/.build/debug.yaml swtest.exe output:

```

**Comment by kjessup** [comment]
This is a problem with using "LocalMirror" forcing everything to compile in swift 3 mode. This is not a CRUD problem and it builds fine with 4.1.1.
